language: python

addons:
  apt:
    packages:
      - python-pip

sudo: true

os: linux

compiler:
  - gcc

before_install:
  - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers
  - pip install pandas
  - cd /tmp && git clone -b tweak/scif https://www.github.com/vsoch/singularity.git && cd singularity
  - ./autogen.sh && ./configure --prefix=/usr/local && make && sudo make install
  - cd $TRAVIS_BUILD_DIR/

install:
  - singularity create --size 8000 container-ftw.img
  - sudo singularity bootstrap container-ftw.img Singularity 
  - singularity create --size 8000 container-ftw.test
  - sudo singularity bootstrap container-ftw.test Singularity.test 
  - mkdir -p assets/data && cp -R $TRAVIS_BUILD_DIR/data assets/data
  - ls assets/data
  - chmod u+x $TRAVIS_BUILD_DIR/test.sh

script:
  - /bin/bash $TRAVIS_BUILD_DIR/test.sh $TRAVIS_BUILD_DIR/container-ftw.results

# containers-ftw.surge.sh

deploy:
  skip_cleanup: true
  provider: surge
  project: ./assets
  domain: containers-ftw.surge.sh
