language: python

addons:
  apt:
    packages:
      - python-pip
      - build-essential
      - libtool
      - squashfs-tools
      - automake
      - autoconf
      - debootstrap
      - uuid-dev
      - libarchive-dev
      - libssl-dev

sudo: true

os: linux

compiler:
  - gcc

before_install:
  - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers
  - pip install pandas
  - cd /tmp && git clone -b development https://www.github.com/singularityware/singularity.git && cd singularity
  - ./autogen.sh && ./configure --prefix=/usr/local && make && sudo make install
  - cd $TRAVIS_BUILD_DIR/

install:
  - chmod u+x $TRAVIS_BUILD_DIR/test.sh
  - make build

script:
  - /bin/bash $TRAVIS_BUILD_DIR/test.sh hello-world

# containers-ftw.surge.sh

deploy:
  skip_cleanup: true
  provider: surge
  project: ./docs
  domain: containers-ftw.surge.sh
