language: python

addons:
  apt:
    packages:
      - python-pip

sudo: true

os: linux

compiler:
  - gcc

before_install:
  - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers
  - pip install pandas
  - cd /tmp && git clone -b tweak/scif https://www.github.com/vsoch/singularity.git && cd singularity
  - echo $PWD && ls
  - ./autogen.sh && ./configure --prefix=/usr/local && make && sudo make install
  - cd $TRAVIS_BUILD_DIR/

install:
  - singularity create --size 8000 container.ftw
  - sudo singularity bootstrap container.ftw Singularity 

script:
  - ./test.sh $TRAVIS_BUILD_DIR/container-ftw.results && python generate_result.py $TRAVIS_BUILD_DIR/container-ftw.results

# containers-ftw.surge.sh

deploy:
  provider: surge
  project: ./analysis
  domain: containers-ftw.surge.sh
